### ISSUE TITLE
[Request] Siren: Blood Curse (True HD Mod)

### ISSUE THREAD

**Issue by HeadstrongWolf** [wh1ter0se-x/ModioX#1]
[Here's the original release thread.](http://psx-scene.com/forums/f180/%5Brel%5D-siren-blood-curse-new-translation-true-hd-crystal-clear-picture-mod-111171/)

Author: Silent_Pavel of PSX Scene
Version: um... 1?
Config: All
Files:  https://drive.google.com/open?id=1kKt4WJv6ZrOhXufSEJluQRoWxVJjRvb7
^This is my own pre-edited file, so no hex edited needed - it's already been done.

I... Don't really know how github works, I'm sorry if this is a mess.

**Comment by wh1ter0se-x** [comment]
Thanks for this! Few questions about as I haven't modded this game before. Where does the _common.dat_ file install to? It's for all regions too?

**Comment by HeadstrongWolf** [comment]
@wh1ter0se-x sorry for the delay in response time, my work schedule is really weird and I'm usually up all night.
So everything about this file is inside the original thread.
The original thread details about how you going to the games files and how to hex edit a certain config for some display settings. It goes into more elaborate detail in that thread which is still online thank God. So are the original files included.
I remember I did it years ago and I saved the file I had so I didn't have to try hex editing ever again. That shit was difficult.
I'm not in front of my PS3 at the moment but I can look up and see exactly what folder this one goes into, but it pretty much just over rights and already existing file and ups the graphical quality.
I don't know about Region honestly - this patch SHOULD work on all Regions for the game, but I can't confirm that. I CAN confirm that it works on the NTSC PSN release.

**Comment by wh1ter0se-x** [comment]
Yes I had noticed you've done the most part, that's amazing thank you. I've found the readme which does help a lot and unfortunately don't have the game installed neither, think I may need to link into the one a little further as I believe it's a psn game, right? So I may need to make an application update to support this and allow for installing the folders of that kind of region, but should be fine. Please do submit all mods that you can find, greatly appreciated of your help.

**Comment by wh1ter0se-x** [comment]
Could I confirm that these are the correct installation paths, starting at root:
```json
"dev_hdd0/game/{REGION}/PS3_GAME/USRDIR/sirenx/data/commonen.dat", 
"dev_hdd0/game/{REGION}/PS3_GAME/USRDIR/sirenx/data/commonuk.dat"
```

Thanks.

**Comment by HeadstrongWolf** [comment]
I think the NTSC PKG, it's just "common", so it may be "commonen" as that's what I remember, but when I look in the games folder, for me, there was no "commonen.dat", BUT there was a "common.dat".

I spent last night finding some MK9 mods - luckily those are easier to install. I'll start a separate thing on those later.

I promise I'll look into it on my PS3. Once I'm in front of my computer I'll be able to tell you more accurately.

But yeah. Just drag and drop into the folder.


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by wh1ter0se-x** [comment]
Thanks for you contributions! I'm going to add a section in the readme for these type of contributions.

At this stage, ModioX is unable install the appropriate _common.dat_ file and depend upon on the users region, so unfortunately all versions of the file will need to be installed to ensure at least the correct one is there. You can always go into the folders yourself and remove the files that aren't necessary afterwards, but I doubt it'll affect anything.

Please be sure to request any other mods you can find.
Regards.

**Comment by wh1ter0se-x** [comment]
@HeadstrongWolf also, I've found and added a mk9 mod but needs to be tested, if ever yiu want to try it out, before I get to soon. Many more other games and mods added too.

**Comment by HeadstrongWolf** [comment]
I'd love to. I may already have.
I'm at work but I'll check it out and upload what I got :)

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
